//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int ALIDaluno { get; set; }
        public int ALtipoAluno { get; set; }
        public string ALemail { get; set; }
        public string ALsenha { get; set; }
        public string ALnome { get; set; }
        public string ALcurso { get; set; }
        public int ALperiodo { get; set; }
        public string ALcampus { get; set; }
        public string ALprojetos { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
