//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliador
    {
        public Avaliador()
        {
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int AVIDavaliador { get; set; }
        public string AVemail { get; set; }
        public string AVsenha { get; set; }
        public string AVnome { get; set; }
        public string AVareaAtuacao { get; set; }
        public string AVformacao { get; set; }
        public string AVprojetosAvaliados { get; set; }
        public string AVProjetosEmAvaliacao { get; set; }
    
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
