//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Avaliador = new HashSet<Avaliador>();
            this.Professor = new HashSet<Professor>();
        }
    
        public int PRIDprojeto { get; set; }
        public string PRalunoLider { get; set; }
        public string PRorientador { get; set; }
        public string PRavaliadorExterno { get; set; }
        public string PRnome { get; set; }
        public string PRdescricao { get; set; }
        public Nullable<double> PRnotaFinal { get; set; }
        public string PRStatusProjeto { get; set; }
        public string PRComentarios { get; set; }
        public string PRAvaliacao { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual ICollection<Avaliador> Avaliador { get; set; }
        public virtual ICollection<Professor> Professor { get; set; }
    }
}
